# Generated by Django 4.0.5 on 2022-07-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='job_posts',
            field=models.ManyToManyField(to='post.jobpost'),
        ),
    ]
